name: LawBridge Backend CD

on:
  push:
    branches:
      - main

permissions:
  contents: read

concurrency:
  group: lawbridge-backend-deployment
  cancel-in-progress: true

jobs:
  deploy:
    name: Build and Deploy Backend
    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image
        run: |
          docker build \
            -t jenithamaxi23/lawbridge-backend:latest \
            -t jenithamaxi23/lawbridge-backend:${{ github.sha }} \
            -f LawBridge.Backend/Dockerfile \
            LawBridge.Backend

      - name: Push Docker image
        run: |
          docker push jenithamaxi23/lawbridge-backend:latest
          docker push jenithamaxi23/lawbridge-backend:${{ github.sha }}

      - name: Deploy Docker image to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: lawbridge-backend
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          images: docker.io/jenithamaxi23/lawbridge-backend:latest